id: P004345
initial_creation_type: ocr
source_metadata:
  id: bdr:W30013
  title: ཚད་མ་རིགས་གཞུང་རྒྱ་མཚོ
  author: ''
  volumes:
    f23acf9b35cc4dfd9240b0930b562c25:
      image_group_id: I5745
      title: ''
      volume_number: 1
      total_pages: 798
      base_file: v001.txt
    8d8ed06aafaa49ca9d5f7e21c3699959:
      image_group_id: I5746
      title: ''
      volume_number: 2
      total_pages: 800
      base_file: v002.txt
