id: I24927182
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:28:41+00:00'
last_modified: '2022-06-07T22:10:02.707355+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30013
  title: ཚད་མ་རིགས་གཞུང་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6A14:
      image_group_id: I5745
      title: ''
      total_pages: 798
      order: 1
      base_file: 6A14.txt
    D778:
      image_group_id: I5746
      title: ''
      total_pages: 800
      order: 2
      base_file: D778.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
